/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainproject;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import trainproject.connection;
import trainproject.homepage;
import trainproject.login;
/**
 *
 * @author user
 */
public class Reservations extends javax.swing.JFrame {

    /**
     * Creates new form Reservations
     */
    public Reservations() {
        initComponents();
      
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextCodeSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DeleteJourneyButton = new javax.swing.JButton();
        ShowButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        Tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "From", "To", "Date", "Car", "Individuals", "Seats", "Class", "Way", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabel);
        if (Tabel.getColumnModel().getColumnCount() > 0) {
            Tabel.getColumnModel().getColumn(0).setResizable(false);
            Tabel.getColumnModel().getColumn(1).setResizable(false);
            Tabel.getColumnModel().getColumn(2).setResizable(false);
            Tabel.getColumnModel().getColumn(3).setResizable(false);
            Tabel.getColumnModel().getColumn(4).setResizable(false);
            Tabel.getColumnModel().getColumn(5).setResizable(false);
            Tabel.getColumnModel().getColumn(6).setResizable(false);
            Tabel.getColumnModel().getColumn(7).setResizable(false);
            Tabel.getColumnModel().getColumn(9).setResizable(false);
        }

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search Using code:");

        TextCodeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCodeSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Your Reservatins ");

        DeleteJourneyButton.setText("Delete Journey");
        DeleteJourneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJourneyButtonActionPerformed(evt);
            }
        });

        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DeleteJourneyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ShowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteJourneyButton)
                            .addComponent(TextCodeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        homepage hp = new homepage();
        hp.setVisible(true);
        this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonActionPerformed

    private void TextCodeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCodeSearchActionPerformed
        DefaultTableModel insert = (DefaultTableModel) Tabel.getModel(); // Table Control
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<> (insert);
        Tabel.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(TextCodeSearch.getText()));
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCodeSearchActionPerformed

    private void DeleteJourneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJourneyButtonActionPerformed

                DefaultTableModel model = (DefaultTableModel) Tabel.getModel(); // Table Control
                if(Tabel.getSelectedRowCount() == 1){
                    int row = Tabel.getSelectedRow();
                    
                    String code_number = model.getValueAt(row,0).toString();
                    String from = model.getValueAt(row, 1).toString();
                    String to = model.getValueAt(row, 2).toString();
                    String Date = model.getValueAt(row, 3).toString();
                    String car_number = model.getValueAt(row, 4).toString();
                    String Individuals = model.getValueAt(row, 5).toString();
                    String seats1 = model.getValueAt(row, 6).toString();
                    String type = model.getValueAt(row, 7).toString();
                    String Round_OneWay = model.getValueAt(row, 8).toString();
                    String Cost = model.getValueAt(row, 9).toString();
                    //String s1="f",s2="f",s3="f",s4="f",s5="f",s6="f",s7="f",s8="f",s9="f",s10="f",s11="f",s12="f",s13="f",s14="f",s15="f",s16="f",s17="f",s18="f",s19="f",s20="f",s21="f",s22="f",s23="f",s24="f",s25="f",s26="f",s27="f",s28="f",s29="f",s30="f",s31="f",s32="f",s33="f",s34="f",s35="f",s36="f",s37="f",s38="f",s39="f",s40="f",s41="f",s42="f",s43="f",s44="f",s45="f",s46="f",s47="f",s48="f";
        String s1="",s2="",s3="",s4="",s5="",s6="",s7="",s8="",s9="",s10="",s11="",s12="",s13="",s14="",s15="",s16="",s17="",s18="",s19="",s20="",s21="",s22="",s23="",s24="",s25="",s26="",s27="",s28="",s29="",s30="",s31="",s32="",s33="",s34="",s35="",s36="",s37="",s38="",s39="",s40="",s41="",s42="",s43="",s44="",s45="",s46="",s47="",s48="";
              String journyNumber="", su="";
        Connection c = connection.connect();
                            try {      
                        Statement st = c.createStatement();
                        ResultSet rs = st.executeQuery("SELECT * FROM reservations WHERE tcode ='"+(String)code_number+"'");
                        if(rs.next())
                        { 
                        journyNumber= rs.getString(3); // get Journey number from
                         su= rs.getString(18).toString(); //car no
                        }else{System.err.println("not found");}
                        switch(su) 
                        {
                        case "1" : su="c1";break;
                        case "2" : su="c2";break;
                        case "3" : su="c3";break;
                        case "4" : su="c4";break;
                        case "5" : su="c5";break;
                        }
                                Statement st1=c.createStatement();
         ResultSet rsa=st1.executeQuery("select * from seats WHERE Journey ='"+journyNumber+"' AND CarNo='"+su+"' ");
           if(rsa.next())
           {
            s1=rsa.getString(3);s6=rsa.getString(8);s11=rsa.getString(13);s16=rsa.getString(18);s21=rsa.getString(23);s26=rsa.getString(28);s31=rsa.getString(33);s36=rsa.getString(38);s41=rsa.getString(43);s45=rsa.getString(47);
            s2=rsa.getString(4);s7=rsa.getString(9);s12=rsa.getString(14);s17=rsa.getString(19);s22=rsa.getString(24);s27=rsa.getString(29);s32=rsa.getString(34);s37=rsa.getString(39);s42=rsa.getString(44);s46=rsa.getString(48);
            s3=rsa.getString(5);s8=rsa.getString(10);s13=rsa.getString(15);s18=rsa.getString(20);s23=rsa.getString(25);s28=rsa.getString(30);s33=rsa.getString(35);s38=rsa.getString(40);s43=rsa.getString(45);s47=rsa.getString(49);
            s4=rsa.getString(6);s9=rsa.getString(11);s14=rsa.getString(16);s19=rsa.getString(21);s24=rsa.getString(26);s29=rsa.getString(31);s34=rsa.getString(36);s39=rsa.getString(41);s44=rsa.getString(46);s48=rsa.getString(50);
            s5=rsa.getString(7);s10=rsa.getString(12);s15=rsa.getString(17);s20=rsa.getString(22);s25=rsa.getString(27);s30=rsa.getString(32);s35=rsa.getString(37);s40=rsa.getString(42);
           }
                    String numberOfSeats[] = seats1.split(",");
                    for(int i = 0 ; i < numberOfSeats.length ; i++){
                        switch(numberOfSeats[i]){
                            case "1" :    s1="f";break;
                            case "2"  :   s2="f";break;
                            case "3"  :   s3="f";break;
                            case "4"  :   s4="f";break;
                            case "5"  :   s5="f";break;
                            case "6"  :   s6="f";break;
                            case "7"  :   s7="f";break;
                            case "8"  :   s8="f";break;
                            case "9"  :   s9="f";break;
                            case "10" :  s10="f";break;
                            case "11" :  s11="f";break;
                            case "12" :  s12="f";break;
                            case "13" :  s13="f";break;
                            case "14" :  s14="f";break;
                            case "15" :  s15="f";break;
                            case "16" :  s16="f";break;
                            case "17" :  s17="f";break;
                            case "18" :  s18="f";break;
                            case "19" :  s19="f";break;
                            case "20" :  s20="f";break;
                            case "21" :  s21="f";break;
                            case "22" :  s22="f";break;
                            case "23" :  s23="f";break;
                            case "24" :  s24="f";break;
                            case "25" :  s25="f";break;
                            case "26" :  s26="f";break;
                            case "27" :  s27="f";break;
                            case "28" :  s28="f";break; 
                            case "29" :  s29="f";break;
                            case "30" :  s30="f";break;
                            case "31" :  s31="f";break;
                            case "32" :  s32="f";break;
                            case "33" :  s33="f";break;
                            case "34" :  s34="f";break;
                            case "35" :  s35="f";break;
                            case "36" :  s36="f";break;
                            case "37" :  s37="f";break;
                            case "38" :  s38="f";break;
                            case "39" :  s39="f";break;
                            case "40" :  s40="f";break;
                            case "41" :  s41="f";break;
                            case "42" :  s42="f";break;
                            case "43" :  s43="f";break;
                            case "44" :  s44="f";break;
                            case "45" :  s45="f";break;
                            case "46" :  s46="f";break;
                            case "47" :  s47="f";break;
                            case "48" :  s48="f";break;
                        }
                    }
                    
                    
                        PreparedStatement s = c.prepareStatement("DELETE from reservations WHERE tcode = '" + (String)code_number + "'");
                        s.execute();
                        PreparedStatement set=c.prepareStatement("UPDATE `seats` SET`s1`='"+s1+"',`s2`='"+s2+"',`s3`='"+s3+"',`s4`='"+s4+"',`s5`='"+s5+"',`s6`='"+s6+"',`s7`='"+s7+"',"
                        + "`s8`='"+s8+"',`s9`='"+s9+"',`s10`='"+s10+"',`s11`='"+s11+"',`s12`='"+s12+"',`s13`='"+s13+"',`s14`='"+s14+"',`s15`='"+s15+"',`s16`='"+s16+"',"
                        + "`s17`='"+s17+"',`s18`='"+s18+"',`s19`='"+s19+"',`s20`='"+s20+"',`s21`='"+s21+"',`s22`='"+s22+"',`s23`='"+s23+"',`s24`='"+s24+"',`s25`='"+s25+"',"
                        + "`s26`='"+s26+"',`s27`='"+s27+"',`s28`='"+s28+"',`s29`='"+s29+"',`s30`='"+s30+"',`s31`='"+s31+"',`s32`='"+s32+"',`s33`='"+s33+"',`s34`='"+s35+"',"
                        + "`s35`='"+s35+"',`s36`='"+s36+"',`s37`='"+s37+"',`s38`='"+s38+"',`s39`='"+s39+"',`s40`='"+s40+"',`s41`='"+s41+"',`s42`='"+s42+"',`s43`='"+s43+"',"
                        + "`s44`='"+s44+"',`s45`='"+s45+"',`s46`='"+s46+"',`s47`='"+s47+"',`s48`='"+s48+"' WHERE Journey='"+journyNumber+"' AND CarNo='"+su+"' "); 
                        set.execute();
                        model.removeRow(Tabel.getSelectedRow());
                    
                            }catch(SQLException ex){
                        JOptionPane.showMessageDialog(this,ex.getMessage());
                    }
                    // i want car number and journey
                    
                    
                    
                }
                else{
                    JOptionPane.showMessageDialog(this,"Please Select Single Row");
                }
        
        
        
    // TODO add your handling code here:
    }//GEN-LAST:event_DeleteJourneyButtonActionPerformed

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        
        String idUser = login.id.getText();
        try{
            Connection connectToDataBase = connection.connect();
            Statement st=connectToDataBase.createStatement();
            DefaultTableModel insert = (DefaultTableModel) Tabel.getModel();
            ResultSet info = st.executeQuery("select * from reservations WHERE id = '"+idUser+"' ");
           ArrayList <String> User = new ArrayList <> ();
            while(info.next()){
                    String code= info.getString(2); //  Code Number 
                    String from= info.getString(12); // From
                    String to= info.getString(13); // TO
                    String date= info.getString(10); // Date 
                    String car= info.getString(18); // Car Number 
                    String ind= info.getString(9); //  Individuals 
                    String seats= info.getString(17); // Seats 
                    String type= info.getString(14); // Type 
                    String RorW=info.getString(16); // Round or One_Way 
                    String cost= info.getString(5); //  Cost
             String data[]={code,from,to,date,car,ind,seats,type,RorW,cost};
                    insert.addRow(data);        
            }
           ShowButton.setEnabled(false);
        }
        
        catch(SQLException x){
            JOptionPane.showMessageDialog(this,"No Connection");
        }
        





        // TODO add your handling code here:
    }//GEN-LAST:event_ShowButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DeleteJourneyButton;
    private javax.swing.JButton ShowButton;
    private javax.swing.JTable Tabel;
    private javax.swing.JTextField TextCodeSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
