/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainproject;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.EncodeHintType;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Win10
 */
public class Reset extends javax.swing.JFrame {

    /**
     * Creates new form Reset
     */
    public Reset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Reservation Receipt");

        area.setEditable(false);
        area.setColumns(20);
        area.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Generate Receipt");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 String name="",age="",isPensioner="",tra="",kilo="",DAY="",MONTH="",pst="",BDate="",discount="",discountReason="",tcode="",journey="",kilometers="",cost="",stime="",atime="",duration="",individuals="",Date="",rdays="",from="",to="",type="",Address="",way="",seat="",car=""; 
 double Disc=0;
 int free=1;
 Reservation r=new Reservation();
 String code=r.getCode();
 String log=login.id.getText();
        try{
            Connection c = connection.connect(); 
            Statement st=c.createStatement();
         ResultSet rs=st.executeQuery("select * from reservations WHERE id='"+log+"'AND tcode = '"+code+"'");
           if(rs.next())
           {
            tcode=rs.getString(2);journey=rs.getString(3);kilometers=rs.getString(4);cost=rs.getString(5);stime=rs.getString(6);atime=rs.getString(7);duration=rs.getString(8);individuals=rs.getString(9);Date=rs.getString(10);rdays=rs.getString(11);from=rs.getString(12);to=rs.getString(13);type=rs.getString(14);Address=rs.getString(15);way=rs.getString(16);seat=rs.getString(17);car=rs.getString(18);
           }
           else{JOptionPane.showMessageDialog(this,"Account Not Found !");}
       
            Statement stat = c.createStatement(); // create connection point 
            ResultSet result = stat.executeQuery("SELECT * FROM `users` WHERE id ="+login.id.getText()); // return all information of particular id
            if(result.next())
            {
            name=result.getString(2);
            age=result.getString(4);
            isPensioner = result.getString(5);
            tra=result.getString(7);
            kilo=result.getString(8);
            DAY=result.getString(9);
            MONTH=result.getString(10);
            pst=result.getString(11);
            BDate=DAY+"/"+MONTH+"/"+"2023";
            }
        }
        catch(SQLException ex){System.out.println(ex.getMessage());}
        
        if(isPensioner.equals("f")){isPensioner="No";} else if(isPensioner.equals("t")){isPensioner="Yes";}
        
         if(Integer.valueOf(tra)>50||Double.valueOf(kilo)>10000)
             {//seats sa=new seats();
              if(BDate.equals(Date)) {discount="100%"; Disc=0; free=0; discountReason="Golden Client\n               travels on the same day as birthday";} 
              else if(pst.equals(to)){discount="50%"; Disc=0.5; discountReason="Golden Client\n                  travels to the preferred station";}
              else{discount="20%"; Disc=0.20; discountReason="Golden Client";}
             }
             else{
            if(isPensioner.equals("f") && Integer.valueOf(age) < 70){
                discount="0%";Disc=1; discountReason="No Discount"; 
            }
            else if(isPensioner.equals("f") && Integer.valueOf(age) > 70){
                discount="50%";Disc=0.50; discountReason="Age more than 70" ;
            }
            else if(isPensioner.equals("t") && Integer.valueOf(age) > 70){
               discount="70%";Disc=0.70; discountReason="Age more than 70\n                  & Pensioner statues indicates true" ;
            }
            else if(isPensioner.equals("t") && Integer.valueOf(age) < 70){
               discount="20%";Disc=0.20; discountReason="Pensioner statues indicates true" ;
            }}
        
         ClassReserv c1=new ClassReserv(); 
            double ocost=c1.getCost(from,to);
 
         area.setText("******************************************\n");
         area.setText(area.getText()+"*           Reservation Receipt         *\n");
         area.setText(area.getText()+"******************************************\n");
         area.setText(area.getText()+"Name :"+name+"\n");
         area.setText(area.getText()+"Id : "+login.id.getText()+"\n");
         area.setText(area.getText()+"Age : "+age+"\n");
         area.setText(area.getText()+"Address : "+Address+"\n");
         area.setText(area.getText()+"Pensioner (Y/N) : "+isPensioner+"\n");
         area.setText(area.getText()+"******************************************\n");
         area.setText(area.getText()+"Ticket Code : "+tcode+"\n");
         area.setText(area.getText()+"From : "+from+"         To : "+to+"\n");
         area.setText(area.getText()+"Reservation done at : "+Date+"\n");
         area.setText(area.getText()+"Remaining Days : "+rdays+"\n");
         area.setText(area.getText()+"Start Time : "+stime+"     Arrive Time : "+atime+"\n");
         area.setText(area.getText()+"Duration : "+duration+" Hours\n");
         area.setText(area.getText()+"Kilometers : "+kilometers+"    Way Type : "+way+"\n");
         area.setText(area.getText()+"Train number : "+journey+"      Car number : "+car+"\n");
         switch(type)
         {
         case "VIP" :
         {
             area.setText(area.getText()+"Train Type : "+type+"\n");
         area.setText(area.getText()+"(The "+type+" increase the cost by 50%)\nDetails : Business class air conditioning \n        & open buffet throughout travel \n        Plus a display screen available \n        throughout the journey \n");
              break;}
         case "First Class" :{
             area.setText(area.getText()+"Train Type : "+type+"\n");
             area.setText(area.getText()+"(The "+type+" increase the cost by 25%)\nDetails : First class air conditioning \n        & open buffet throughout travel\n");
              break;} 
         case "Second Class" : {
             area.setText(area.getText()+"Train Type : "+type+"\n");
             area.setText(area.getText()+"(The "+type+" increase the cost by 5%)\nDetails : Second class air conditioning\n");
              break;} 
         case "Noraml Class" : {
             area.setText(area.getText()+"Train Type : "+type+"\n(The "+type+" increase the cost by 0%)");
              break;} 
         }
         area.setText(area.getText()+"Indviduals no. : "+individuals+"     Seats no. : "+seat.substring(0,seat.length()-1)+"\n");
         area.setText(area.getText()+"Original Cost : "+ocost+" $\n");
         area.setText(area.getText()+"Total Cost : "+cost+" $\n");
         area.setText(area.getText()+"Discount : "+discount+"\n");
         area.setText(area.getText()+"Discount Reason : "+discountReason+"\n");
         area.setText(area.getText()+"******************************************\n");
         double FCOST=Double.parseDouble(cost)*Disc;
         area.setText(area.getText()+"Final Cost : "+(Double.parseDouble(cost)-FCOST)*free+" EGP\n");
         area.setText(area.getText()+"******************************************\n");
         area.setText(area.getText()+"                 هيئة سكك حديد مصر\n");
          area.setText(area.getText()+"                     Signature\n");
          area.setText(area.getText()+"                       س ح م");
try {
     String QrCodeData=area.getText();
     String filepath="D:\\Projects\\Java\\Netbeans\\TrainProject\\QrCode\\qr.png";
     String charset="UTF-8";
     Map<EncodeHintType,ErrorCorrectionLevel> hintMap=new HashMap<EncodeHintType,ErrorCorrectionLevel>();
     hintMap.put(EncodeHintType.ERROR_CORRECTION,ErrorCorrectionLevel.L);
     BitMatrix matrix=new MultiFormatWriter().encode(new String(QrCodeData.getBytes(charset),charset),BarcodeFormat.QR_CODE,500,500,hintMap);
     MatrixToImageWriter.writeToFile(matrix,filepath.substring(filepath.lastIndexOf('.')+1),new File(filepath));
     JOptionPane.showMessageDialog(this,"Generated Successfully at "+filepath);
     JFrame frame=new JFrame();
     ImageIcon icon=new ImageIcon("D:\\Projects\\Java\\Netbeans\\TrainProject\\QrCode\\qr.png");
     JLabel label=new JLabel(icon);
     frame.add(label);
      frame.setSize(500,500);
      frame.setVisible(true);
      frame.setLocation(800, 400);
     //qrarea.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
             }catch(Exception e){System.out.println(e.getMessage());}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            area.print();
        } catch (Exception ex) {
           System.out.println();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       homepage h=new homepage();
       h.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

